# Generated by Django 3.2.7 on 2021-10-05 06:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_article_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
