# Generated by Django 3.2.7 on 2021-10-05 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_article_date_posted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date_posted',
            field=models.DateTimeField(default='2021-10-05 07:47:43'),
        ),
    ]
